### ISSUE TITLE
第23回のエラーについて共有

### ISSUE THREAD

**Issue by galaxycometplanet** [galaxycometplanet/-day2#9]

**Comment by daytomari** [comment]
コメントのテストです。

**Comment by galaxycometplanet** [comment]
JCTreeの問題はLombokのバージョンによるエラーだったようです。Discordの講師の方から1.18.30より古いとこのような現象になると御指南お受けしました。

ありがとうございました

> コメントのテストです。

**Comment by galaxycometplanet** [comment]
> コメントのテストです。

**Comment by daytomari** [comment]
フクノさん、ご連絡ありがとうございました。
どうしてもエラーの原因が見つからず、苦戦していたところでした(;^_^A
